apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
  labels:
    version: v2
type: Opaque
data:
  load_balancer_ip_range: "2a02:8424:8502:6d01:b133:2c50:5e4::/112"
  sftpgo_domain: "sftpgo.local"
