---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/RedbeanGit/homelab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab
  namespace: default
spec:
  interval: 10m0s
  path: ./flux/clusters/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
