creation_rules:
  - path_regex: flux/clusters/.*/config/.*\.ya?ml
    age:
      - age1fe4qsmk5psclxsct8fmq5lenama3zt7vt35arsxqslxlskcp9pjsup39qj
      - age1rp8qrv3nek4se3a23hw4kzy0k9yh4spjgkcx6rj8wg0ddd3yl92qyqlujg
    encrypted_regex: "^(data|stringData)$"
