apiVersion: v1
kind: PersistentVolume
metadata:
  name: hytale-data-pv
  labels:
    app: hytale
    component: hytale-data
    managed-by: manual
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /srv/hytale/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hytale-backups-pv
  labels:
    app: hytale
    component: hytale-backups
    managed-by: manual
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /srv/hytale/backups
    type: DirectoryOrCreate
