apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: kyverno
      version: "3.6.0-rc.1"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 5m
  releaseName: kyverno
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    admissionController:
      container:
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
