apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicy
metadata:
  name: ngrok-annotate-kubernetes-service
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["services"]
  matchConditions:
    - name: only-default-kubernetes-service
      expression: 'object.metadata.name == "kubernetes" && request.namespace == "default"'
  failurePolicy: Ignore
  reinvocationPolicy: IfNeeded
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: |
          [
            JSONPatch{
              op: "add",
              path: "/metadata/annotations/" + jsonpatch.escapeKey("k8s.ngrok.com/app-protocols"),
              value: "{\"https\":\"https\"}"
            }
          ]
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: ngrok-annotate-kubernetes-service-binding
spec:
  policyName: ngrok-annotate-kubernetes-service
  matchResources:
    namespaceSelector:
      matchLabels: {}
