apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ngrok-system-patches
spec:
  interval: 10m
  prune: false
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  path: ./flux/infrastructure/ngrok/system
  patches:
    - target:
        group: ""
        version: v1
        kind: Service
        name: kubernetes
        namespace: default
      patchType: json6902
      patch: |
        - op: add
          path: /metadata/annotations
          value: {}
        - op: add
          path: /metadata/annotations/k8s.ngrok.com~1app-protocols
          value: "{\"https\":\"https\"}"
