apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: papermc
  labels:
    app: papermc
spec:
  automountServiceAccountToken: false
  serviceName: papermc
  replicas: 1
  selector:
    matchLabels:
      app: papermc
  template:
    metadata:
      labels:
        app: papermc
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: papermc
          image: redbeandock/papermc-server:1.21.10-117-temurin21
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: "-Xms4G -Xmx6G"
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
            - name: rcon
              containerPort: 25575
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "6Gi"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
