apiVersion: v1
kind: PersistentVolume
metadata:
  name: papermc-pv
  labels:
    app: papermc
    component: papermc-data
    managed-by: manual
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /srv/papermc/data
    type: DirectoryOrCreate
