apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hytale
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/apps/hytale
  targetNamespace: hytale
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
