apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ngrok-operator
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: ngrok-operator
      version: "0.20.0"
      sourceRef:
        kind: HelmRepository
        name: ngrok
        namespace: flux-system
      interval: 5m
  releaseName: ngrok-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    credentials:
      secret:
        name: ngrok-credentials
