apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure/kyverno
  targetNamespace: kyverno
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
