apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure/metallb
  targetNamespace: metallb-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
