apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-ip-pools
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure/metallb-ip-pools
  targetNamespace: metallb-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  dependsOn:
    - name: metallb
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
