apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ngrok
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure/ngrok
  targetNamespace: infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  dependsOn:
    - name: homelab
    - name: ngrok-operator
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars
